theme: jekyll-theme-cayman
title: Guanbin Chen's homepage
description: >
  最近正在寻找工作，C++开发、后端或算法，国内和国外均可。如有工作机会，请联系邮箱1249591860@qq.com。
  
  Currently looking for job opportunities in C++ development, back-end development or algorithms, open to opportunities both domestically and internationally. If you have any job openings, please contact me at 1249591860@qq.com.
